language: java
addons:
  sonarcloud:
    organization: "csys-fresher-batch-2019"
    token:
      secure: "4a375ce53f26e281562795e2a65f25a24d722970"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=csys-fresher-batch-2019_placementapp-nivedha
